Fix an exception from Chrome-reload
Error: Google Chrome got an error: Can't get tab 1 of some window
whose URL = \"http://example.com\". Invalid index.

`first tab of some window whose URL is #{url}' may be missing value.

`first tab of windows whose URL is #{url}' returns a list, for example,

  {missing value, tab id 2382 of window id 1364 of application "Google
  Chrome", missing value, missing value}

The length is the number of Chrome windows. Windows with no matching
tab is missing value in the list.